module.exports = {
  apps: [
    {
      name: 'errandify-backend',
      script: './backend/node_modules/.bin/tsx',
      args: 'watch backend/src/index.ts',
      cwd: '/Users/celestia/Claude code/260616 Errandify WebApp',
      instances: 1,
      exec_mode: 'fork',
      watch: ['backend/src'],
      ignore_watch: ['node_modules', 'dist'],
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        DATABASE_URL: 'postgresql://localhost/errandify',
        JWT_SECRET: 'your-secret-key-change-in-production',
      },
      error_file: '/tmp/errandify-backend-error.log',
      out_file: '/tmp/errandify-backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
    {
      name: 'errandify-frontend',
      script: 'npm',
      args: 'run dev',
      cwd: '/Users/celestia/Claude code/260616 Errandify WebApp/frontend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        VITE_API_URL: 'http://localhost:3000',
      },
      error_file: '/tmp/errandify-frontend-error.log',
      out_file: '/tmp/errandify-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
  ],
};
