app = "errandify-webapp"
primary_region = "sin"

[build]
  builder = "heroku"
  buildpacks = ["heroku/nodejs"]

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_rollback = true

  [services.concurrency]
    type = "connections"
    hard_limit = 1024
    soft_limit = 512

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    timeout = "5s"
