import db from '../db.js';

/**
 * Migration 029 — make job_applications writable from the application form.
 *
 * The form at /apply collects ten steps of detail, assembles an
 * `applicationData` object, and then discards it — the submit handler's only
 * network call is a commented-out line reading
 *   // In production: await fetch('/api/applications/submit', ...)
 * before it sets submitted=true and shows "Application submitted successfully!".
 *
 * So every applicant who has ever completed that form was told it worked and
 * left no record. That is worse than a failure they could see and retry. The
 * endpoint is being built; this migration covers the gaps in the table.
 *
 * 1. application_id is NOT NULL with no default and nothing generating it, so
 *    any insert fails. Generated by trigger from the row id, matching the
 *    CASE-000123 pattern in migration 020, so the reference is stable and
 *    unique without a second round trip.
 *
 * 2. employment_history, education_records and referee_contacts are collected
 *    by the form and have nowhere to go. Added as jsonb rather than dropped:
 *    silently losing an applicant's job history is the same class of bug as
 *    silently losing the whole application.
 *
 * NRIC: the column already exists and recruitment has a genuine need for it,
 * so it is stored as entered rather than hashed — unlike the Singpass path,
 * where the UINFIN is hashed and never persisted. Worth a PDPA retention
 * decision (how long unsuccessful applications are kept) before this goes live.
 */
export async function up() {
  await db.query(`ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS employment_history JSONB DEFAULT '[]'::jsonb`);
  await db.query(`ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS education_records JSONB DEFAULT '[]'::jsonb`);
  await db.query(`ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS referee_contacts JSONB DEFAULT '[]'::jsonb`);

  await db.query(`
    CREATE OR REPLACE FUNCTION set_job_application_id() RETURNS TRIGGER AS $$
    BEGIN
      IF NEW.application_id IS NULL OR NEW.application_id = '' THEN
        NEW.application_id := 'APP-' || LPAD(NEW.id::text, 6, '0');
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql
  `);

  // BEFORE INSERT is correct here: Postgres applies column defaults (the
  // serial nextval) before BEFORE-row triggers fire, so NEW.id is already
  // populated and can be formatted without a second UPDATE.
  await db.query(`DROP TRIGGER IF EXISTS trg_job_application_id ON job_applications`);
  await db.query(`
    CREATE TRIGGER trg_job_application_id
      BEFORE INSERT ON job_applications
      FOR EACH ROW EXECUTE FUNCTION set_job_application_id()
  `);

  // The trigger needs an id to build from; give application_id a placeholder
  // default so the NOT NULL constraint is satisfied at insert time.
  await db.query(`ALTER TABLE job_applications ALTER COLUMN application_id DROP NOT NULL`);

  await db.query(`CREATE INDEX IF NOT EXISTS idx_job_applications_status ON job_applications(status, submitted_at DESC)`);
  await db.query(`CREATE INDEX IF NOT EXISTS idx_job_applications_email ON job_applications(email)`);

  console.log('[029] ✅ job_applications intake ready');
}

export async function down() {
  await db.query('DROP TRIGGER IF EXISTS trg_job_application_id ON job_applications');
  await db.query('DROP FUNCTION IF EXISTS set_job_application_id()');
}

if (process.argv[1] && process.argv[1].includes('029_job_application_intake')) {
  up().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
}
