/**
 * Singapore Public Holiday Service
 * Auto-marks staff as unavailable on public holidays
 */

export interface PublicHoliday {
  date: string; // YYYY-MM-DD
  name: string;
  emoji: string;
}

// Singapore Public Holidays 2026
export const SINGAPORE_HOLIDAYS_2026: PublicHoliday[] = [
  { date: '2026-01-26', name: 'Thaipusam', emoji: '🙏' },
  { date: '2026-02-10', name: 'Chinese New Year', emoji: '🧧' },
  { date: '2026-02-11', name: 'Chinese New Year (Day 2)', emoji: '🧧' },
  { date: '2026-04-10', name: 'Good Friday', emoji: '✝️' },
  { date: '2026-05-01', name: "Workers' Day", emoji: '👷' },
  { date: '2026-05-24', name: 'Vesak Day', emoji: '🙏' },
  { date: '2026-07-07', name: 'Hari Raya Puasa', emoji: '🌙' },
  { date: '2026-08-09', name: 'National Day', emoji: '🇸🇬' },
  { date: '2026-08-17', name: 'Hari Raya Haji', emoji: '🌙' },
  { date: '2026-10-29', name: 'Deepavali', emoji: '🪔' },
  { date: '2026-12-25', name: 'Christmas Day', emoji: '🎄' },
];

/**
 * Get holidays for a specific month/year
 */
export function getHolidaysForMonth(year: number, month: number): PublicHoliday[] {
  return SINGAPORE_HOLIDAYS_2026.filter(h => {
    const [hYear, hMonth] = h.date.split('-').map(Number);
    return hYear === year && hMonth === month;
  });
}

/**
 * Get all holidays in a date range
 */
export function getHolidaysInRange(startDate: string, endDate: string): PublicHoliday[] {
  const start = new Date(startDate);
  const end = new Date(endDate);

  return SINGAPORE_HOLIDAYS_2026.filter(h => {
    const hDate = new Date(h.date);
    return hDate >= start && hDate <= end;
  });
}

/**
 * Check if a date is a public holiday
 */
export function isPublicHoliday(dateStr: string): PublicHoliday | null {
  return SINGAPORE_HOLIDAYS_2026.find(h => h.date === dateStr) || null;
}

/**
 * Auto-create holiday unavailability records
 * Called when staff applies for leave or admin updates operating hours
 */
export function generateHolidayUnavailability(startDate: string, endDate: string) {
  const holidays = getHolidaysInRange(startDate, endDate);

  return holidays.map(holiday => ({
    id: `holiday-${holiday.date}`,
    date: holiday.date,
    staffId: null, // null = applies to ALL staff
    reason: `🇸🇬 Singapore Public Holiday - ${holiday.name}`,
    type: 'public-holiday' as const,
    isAutoGenerated: true,
    appliesTo: 'all-staff' as const,
    period: 'full-day' as const,
    holiday,
  }));
}

/**
 * Get next upcoming holiday
 */
export function getNextHoliday(): PublicHoliday | null {
  const today = new Date().toISOString().split('T')[0];
  return SINGAPORE_HOLIDAYS_2026.find(h => h.date > today) || null;
}

/**
 * Format holiday for display
 */
export function formatHolidayDisplay(holiday: PublicHoliday): string {
  const date = new Date(holiday.date);
  return `${holiday.emoji} ${holiday.name} (${date.toLocaleDateString('en-SG', {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })})`;
}

/**
 * Get holiday statistics for a period
 */
export function getHolidayStats(startDate: string, endDate: string) {
  const holidays = getHolidaysInRange(startDate, endDate);
  return {
    total: holidays.length,
    holidays,
    totalDays: holidays.length,
  };
}
